[package]
name = "custom-behaviour-and-context"
version = "0.1.0"
edition = "2024"
publish = false

[package.metadata.release]
release = false

[dependencies]
tokio.workspace = true
futures.workspace = true
connexa = { path = "../../" }